### ISSUE TITLE
AutoprovisionConf.php и crontab

### ISSUE THREAD

**Issue by ravenich** [mikopbx/ModuleAutoprovision#5]
AutoprovisionConf.php создает задачу в crontab такого вида: 
`*/1 * * * * /usr/bin/php -f /storage/usbdisk1/mikopbx/custom_modules/ModuleAutoprovision/Lib/WorkerProvisioningServerPnP.php`
Но WorkerProvisioningServerPnP.php запускается только если count($argv) > 1), подскажите в чем смысл запуска такой конструкции каждую минуту?
Также в функции function start($params) в WorkerProvisioningServerPnP.php мы пытаемся получить $action = $argv[1] ?? ''; хотя получаем $params и из консоли запуск скрипта не работает.

**Comment by boffart** [comment]
Действительно есть ошибки с задачей. 
В новой версии будет исправлено. Задачи в Cron не будет.
